"""empty message

Revision ID: 04c9826dddd3
Revises: 3f42fa66c767
Create Date: 2022-03-22 10:03:14.121382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c9826dddd3'
down_revision = '3f42fa66c767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('msg_status', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'msg_status')
    # ### end Alembic commands ###
