"""empty message

Revision ID: a452c3ab29fc
Revises: b9b6576ea493
Create Date: 2022-03-30 10:51:56.899316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a452c3ab29fc'
down_revision = 'b9b6576ea493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'message', 'worker', ['w_id'], ['id'])
    op.create_foreign_key(None, 'timespent', 'worker', ['w_id'], ['id'])
    op.create_foreign_key(None, 'worker_behavior', 'worker', ['w_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worker_behavior', type_='foreignkey')
    op.drop_constraint(None, 'timespent', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    # ### end Alembic commands ###
