"""empty message

Revision ID: eb0ceab5b68d
Revises: 
Create Date: 2022-03-30 13:15:11.707177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0ceab5b68d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prolific_id', sa.String(length=50), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('w_id', sa.Integer(), nullable=True),
    sa.Column('worker_utterance', sa.String(length=500), nullable=False),
    sa.Column('msg_status', sa.String(length=500), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['w_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timespent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('w_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=500), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['w_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_behavior',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('w_id', sa.Integer(), nullable=True),
    sa.Column('b_name', sa.String(length=200), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['w_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_behavior')
    op.drop_table('timespent')
    op.drop_table('message')
    op.drop_table('worker')
    op.drop_table('sessions')
    # ### end Alembic commands ###
